import React, { useState } from "react";
import { ShieldAlert, Building, Briefcase, User, Users, ChevronRight, MessageSquare, ArrowRight, Mail, Calendar, Database, CreditCard, Layers, Eye, CheckCircle2, DollarSign, Activity, FileText, CheckSquare, Clock, MapPin } from "lucide-react";
const ROLES_DATA = [{
  id: "company-admin",
  name: "Company Admin",
  badge: "Workspace Owner",
  icon: Building,
  color: "border-t-blue-600 bg-blue-50/50 hover:bg-blue-50 text-blue-700",
  metrics: {
    "Total Projects": "240+",
    "Team Members": "480+",
    "Attendance Rate": "97.2%",
    "Productivity Score": "94%"
  },
  steps: [{
    num: 1,
    title: "Workspace Setup",
    desc: "Define profile, set working days, holidays, and regional calendars."
  }, {
    num: 2,
    title: "Department Setup",
    desc: "Establish core organizational departments, divisions, and groups."
  }, {
    num: 3,
    title: "Team Management",
    desc: "Invite core team members and allocate their structural roles."
  }, {
    num: 4,
    title: "Role & Permission",
    desc: "Configure customized security roles and granular permissions."
  }, {
    num: 5,
    title: "Project Creation",
    desc: "Create projects, set target budgets, and outline timelines."
  }, {
    num: 6,
    title: "Resource Allocation",
    desc: "Assign Project Managers and match resources to project pools."
  }]
}, {
  id: "project-manager",
  name: "Project Manager",
  badge: "Project Owner",
  icon: Briefcase,
  color: "border-t-indigo-600 bg-indigo-50/50 hover:bg-indigo-50 text-indigo-700",
  metrics: {
    "On-Time Delivery": "92.5%",
    "Budget Accuracy": "96%",
    "Active Milestones": "42",
    "Client Satisfaction": "4.8/5"
  },
  steps: [{
    num: 1,
    title: "Receive Project",
    desc: "Acknowledge scope, requirements, and budgets from the Company Admin."
  }, {
    num: 2,
    title: "Requirement Gathering",
    desc: "Collect client requirements and draft technical spec docs."
  }, {
    num: 3,
    title: "Plan Project",
    desc: "Break down milestones, set Gantt schedules, sprints, and task backlogs."
  }, {
    num: 4,
    title: "Assign Tasks",
    desc: "Delegate cards to team members based on capacity and skills."
  }, {
    num: 5,
    title: "Track Progress",
    desc: "Monitor task statuses, blockers, and time logged on dashboards."
  }, {
    num: 6,
    title: "Upload Deliverables",
    desc: "Acknowledge work completed and bundle outputs for review."
  }, {
    num: 7,
    title: "Client Portal Access",
    desc: "Create a secure invite link to bring clients into the loop."
  }, {
    num: 8,
    title: "Collect Feedback",
    desc: "Receive, filter, and assign client revisions and feedback."
  }, {
    num: 9,
    title: "Final Delivery",
    desc: "Attain final client signoff and close the project node."
  }]
}, {
  id: "employee",
  name: "Employee",
  badge: "Team Member",
  icon: User,
  color: "border-t-emerald-600 bg-emerald-50/50 hover:bg-emerald-50 text-emerald-700",
  metrics: {
    "Tasks Completed": "3,400+",
    "Avg. Cycle Time": "2.4 Days",
    "Time Tracked": "18k Hours",
    "Shift Attendance": "98.1%"
  },
  steps: [{
    num: 1,
    title: "Login & Dashboard",
    desc: "Check individual tasks, priorities, calendar, and announcements."
  }, {
    num: 2,
    title: "View Assigned Tasks",
    desc: "Inspect card details, requirements, checklists, and timelines."
  }, {
    num: 3,
    title: "Start Work",
    desc: "Click \"Start\" on cards to trigger the work status and record logs."
  }, {
    num: 4,
    title: "Update Progress",
    desc: "Post comments, drag cards, log worked hours, and upload attachments."
  }, {
    num: 5,
    title: "Collaborate",
    desc: "Discuss challenges in team threads, tag peers, and share assets."
  }, {
    num: 6,
    title: "Attendance Tracking",
    desc: "Check-in and check-out of work shifts with geo-location/IP tracking.",
    icon: MapPin
  }, {
    num: 7,
    title: "Submit Work",
    desc: "Upload file links and submit completed tasks to the manager for validation."
  }, {
    num: 8,
    title: "Manager Review",
    desc: "Respond to manager feedbacks and resolve review comments."
  }]
}, {
  id: "client-portal",
  name: "Client Portal",
  badge: "Client / Customer",
  icon: Users,
  color: "border-t-rose-600 bg-rose-50/50 hover:bg-rose-50 text-rose-700",
  metrics: {
    "Invited Clients": "840+",
    "Active Sessions": "120/hr",
    "Feedback Turnaround": "4.2 hrs",
    "Invoice Paid Rate": "98.5%"
  },
  steps: [{
    num: 1,
    title: "Receive Invitation",
    desc: "Receive automated onboarding email links generated by the PM."
  }, {
    num: 2,
    title: "Access Portal",
    desc: "Create secure account login credentials to view dedicated workspace."
  }, {
    num: 3,
    title: "Dashboard Overview",
    desc: "Inspect high-level timelines, metrics, budgets, and milestones."
  }, {
    num: 4,
    title: "Track Progress",
    desc: "Watch task lists update live as developers commit code."
  }, {
    num: 5,
    title: "Review Deliverables",
    desc: "Examine docs, design previews, and staging links directly."
  }, {
    num: 6,
    title: "Provide Feedback",
    desc: "Approve work items or submit bulleted revisions with screenshots."
  }, {
    num: 7,
    title: "Invoices & Payments",
    desc: "View detailed bills, verify additional expenses, and pay via Stripe/PayPal."
  }, {
    num: 8,
    title: "Final Approval",
    desc: "Close out projects and provide satisfaction survey feedback."
  }]
}];
const DATA_FLOW = [{
  icon: FileText,
  label: "Requirements"
}, {
  icon: CheckSquare,
  label: "Tasks"
}, {
  icon: Layers,
  label: "Work"
}, {
  icon: Eye,
  label: "Review"
}, {
  icon: CheckCircle2,
  label: "Deliverables"
}, {
  icon: ShieldAlert,
  label: "Approval"
}, {
  icon: CreditCard,
  label: "Payment"
}, {
  icon: Clock,
  label: "Closure"
}];
const COLLAB_FEATURES = [{
  label: "Discussion"
}, {
  label: "Comments"
}, {
  label: "Mentions"
}, {
  label: "File Sharing"
}, {
  label: "Notifications"
}];
const INTEGRATIONS = [{
  icon: Mail,
  label: "Email"
}, {
  icon: Calendar,
  label: "Calendar"
}, {
  icon: Database,
  label: "Storage"
}, {
  icon: CreditCard,
  label: "Payments"
}, {
  icon: Layers,
  label: "APIs"
}];
const LIFECYCLE_STEPS = [{
  step: "01",
  title: "Initiation",
  desc: "Project request & approval"
}, {
  step: "02",
  title: "Planning",
  desc: "Requirement, scope & plan"
}, {
  step: "03",
  title: "Execution",
  desc: "Development & task execution"
}, {
  step: "04",
  title: "Monitoring",
  desc: "Track progress, time & stats"
}, {
  step: "05",
  title: "Review",
  desc: "Review, testing & QA checks"
}, {
  step: "06",
  title: "Delivery",
  desc: "Deliverables to client"
}, {
  step: "07",
  title: "Approval",
  desc: "Client approval & feedback"
}, {
  step: "08",
  title: "Payment",
  desc: "Invoice, payment & settlement"
}, {
  step: "09",
  title: "Closure",
  desc: "Project closure & report"
}];
export default function WorkflowExplorer() {
  const [activeTab, setActiveTab] = useState("roles");
  const [activeRole, setActiveRole] = useState("company-admin");
  const selectedRoleData = ROLES_DATA.find(r => r.id === activeRole);
  return <section id="workflow" className="py-24 bg-white border-t border-slate-200 relative overflow-hidden"> <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10"> {} <div className="reveal text-center max-w-3xl mx-auto mb-12"> <span className="text-xs font-semibold uppercase tracking-widest text-indigo-600 bg-indigo-50 px-3 py-1 rounded-full border border-indigo-100"> End-To-End Workflow </span> <h2 className="mt-4 text-3xl sm:text-4xl font-extrabold font-display text-slate-900 tracking-tight"> How Syncra Powers Your Business </h2> <p className="mt-4 text-lg text-slate-600"> Syncra connects every stakeholders from Admin to Client in a unified workflow. Discover how we deliver complete visibility, compliance, and velocity. </p> </div> {} <div className="reveal bg-gradient-to-r from-indigo-50 to-cyan-50 rounded-2xl p-6 mb-12 border border-indigo-100 text-center max-w-4xl mx-auto"> <h3 className="text-sm font-bold uppercase tracking-wider text-indigo-800 font-display mb-2">Our Vision</h3> <p className="text-slate-700 italic font-medium leading-relaxed"> "To build the world’s most transparent, automated, and collaborative project engine—bridging the gap between company vision, manager allocation, developer execution, and client validation." </p> </div> {} <div className="reveal flex justify-center mb-10"> <div className="bg-slate-100 p-1.5 rounded-full flex space-x-1 border border-slate-200"> <button onClick={() => setActiveTab("roles")} className={`px-6 py-2.5 rounded-full text-xs font-semibold tracking-wide transition-all cursor-pointer ${activeTab === "roles" ? "bg-white text-indigo-600 shadow-sm" : "text-slate-600 hover:text-slate-900"}`}> 1. Organization Roles </button> <button onClick={() => setActiveTab("lifecycle")} className={`px-6 py-2.5 rounded-full text-xs font-semibold tracking-wide transition-all cursor-pointer ${activeTab === "lifecycle" ? "bg-white text-indigo-600 shadow-sm" : "text-slate-600 hover:text-slate-900"}`}> 2. 9-Step Project Lifecycle </button> <button onClick={() => setActiveTab("flow")} className={`px-6 py-2.5 rounded-full text-xs font-semibold tracking-wide transition-all cursor-pointer ${activeTab === "flow" ? "bg-white text-indigo-600 shadow-sm" : "text-slate-600 hover:text-slate-900"}`}> 3. Data Flows & Collab </button> </div> </div> {} {activeTab === "roles" && <div className="space-y-8 animate-fade-in"> {} <div className="grid grid-cols-2 md:grid-cols-4 gap-3 max-w-5xl mx-auto"> {ROLES_DATA.map(role => {
            const Icon = role.icon;
            const isActive = activeRole === role.id;
            return <button key={role.id} onClick={() => setActiveRole(role.id)} className={`flex flex-col items-center justify-center p-4 rounded-xl border transition-all text-center cursor-pointer ${isActive ? "bg-white border-indigo-600 shadow-lg ring-2 ring-indigo-100 scale-105" : "bg-slate-50 hover:bg-slate-100 border-slate-200"}`}> <Icon className={`mb-2 ${isActive ? "text-indigo-600" : "text-slate-400"}`} size={24} /> <span className={`text-xs font-bold font-display ${isActive ? "text-indigo-600" : "text-slate-700"}`}> {role.name} </span> <span className="text-[9px] text-slate-400 font-medium mt-1">{role.badge}</span> </button>;
          })} </div> {} {selectedRoleData && <div className="grid grid-cols-1 lg:grid-cols-3 gap-8 bg-slate-50 border border-slate-200/80 rounded-2xl p-6 sm:p-8 max-w-5xl mx-auto shadow-md"> {} <div className="lg:col-span-1 space-y-6 lg:border-r lg:border-slate-200 lg:pr-8 flex flex-col justify-between"> <div> <div className="inline-flex items-center space-x-2 bg-indigo-50 border border-indigo-100 px-3 py-1 rounded-full text-indigo-700 text-xs font-bold font-display mb-3"> <selectedRoleData.icon size={14} /> <span>{selectedRoleData.name} Interface</span> </div> <h3 className="text-xl font-extrabold font-display text-slate-800"> {selectedRoleData.name} </h3> <p className="text-slate-400 text-xs font-medium uppercase tracking-wider mt-1">{selectedRoleData.badge}</p> <p className="mt-4 text-sm text-slate-600 leading-relaxed"> This user acts as the {selectedRoleData.badge} of the project framework, handling key structural gates and workflows shown to the right. </p> </div> {} <div className="bg-white border border-slate-200 rounded-xl p-4 space-y-3"> <h4 className="text-xs font-bold text-slate-800 uppercase tracking-wider font-display flex items-center"> <Activity size={12} className="text-indigo-500 mr-1.5" /> Performance Metrics </h4> <div className="grid grid-cols-2 gap-3 pt-1"> {Object.entries(selectedRoleData.metrics).map(([key, val]) => <div key={key} className="bg-slate-50 p-2.5 rounded-lg border border-slate-100"> <span className="text-[10px] text-slate-500 block leading-tight">{key}</span> <span className="text-sm font-bold text-slate-800">{val}</span> </div>)} </div> </div> </div> {} <div className="lg:col-span-2 space-y-4"> <h4 className="text-xs font-bold text-slate-800 uppercase tracking-wider font-display"> Standard Operational Workflow ({selectedRoleData.steps.length} Steps) </h4> <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 max-h-[380px] overflow-y-auto pr-1"> {selectedRoleData.steps.map(step => <div key={step.num} className={`p-4 bg-white border border-slate-200 rounded-xl flex items-start space-x-3 transition-colors ${step.icon ? "border-emerald-200 bg-emerald-50/10" : ""}`}> <span className={`text-[10px] font-bold w-5 h-5 flex items-center justify-center rounded-full shrink-0 ${step.icon ? "bg-emerald-100 text-emerald-700" : "bg-indigo-50 text-indigo-700"}`}> {step.icon ? <step.icon size={10} /> : step.num} </span> <div> <h5 className="text-xs font-bold text-slate-800 flex items-center"> {step.title} {step.icon && <span className="ml-1.5 text-[8px] bg-emerald-100 text-emerald-800 font-extrabold px-1 rounded uppercase tracking-widest">Crucial</span>} </h5> <p className="text-[11px] text-slate-500 mt-1 leading-relaxed">{step.desc}</p> </div> </div>)} </div> </div> </div>} </div>} {} {activeTab === "lifecycle" && <div className="space-y-12 animate-fade-in"> {} <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 max-w-5xl mx-auto"> {LIFECYCLE_STEPS.map((lifecycle, index) => <div key={lifecycle.step} className="bg-slate-50 hover:bg-slate-100/70 border border-slate-200/80 rounded-2xl p-5 relative overflow-hidden transition-all group"> {} <span className="absolute top-2 right-4 text-5xl font-extrabold font-display text-slate-200/50 select-none group-hover:text-indigo-100/50 transition-colors"> {lifecycle.step} </span> <div className="flex items-center space-x-2.5 mb-2 relative z-10"> <span className="w-6 h-6 flex items-center justify-center bg-indigo-100 text-indigo-700 font-bold text-xs rounded-full"> {lifecycle.step} </span> <h4 className="font-bold text-slate-800 text-sm tracking-wide font-display"> {lifecycle.title} </h4> </div> <p className="text-xs text-slate-500 leading-relaxed relative z-10"> {lifecycle.desc} </p> </div>)} </div> {} <div className="bg-slate-50 p-6 rounded-2xl border border-slate-200/70 max-w-5xl mx-auto flex items-center justify-between overflow-x-auto gap-4 scrollbar-none"> {LIFECYCLE_STEPS.map((lifecycle, index) => <React.Fragment key={lifecycle.step}> <div className="flex flex-col items-center shrink-0"> <div className="w-9 h-9 rounded-full bg-indigo-50 border border-indigo-100 text-indigo-700 font-bold text-xs flex items-center justify-center shadow-sm"> {lifecycle.step} </div> <span className="text-[10px] font-semibold text-slate-600 mt-1">{lifecycle.title}</span> </div> {index < LIFECYCLE_STEPS.length - 1 && <ChevronRight size={14} className="text-slate-400 shrink-0" />} </React.Fragment>)} </div> </div>} {} {activeTab === "flow" && <div className="space-y-8 animate-fade-in max-w-5xl mx-auto"> {} <div className="grid grid-cols-1 md:grid-cols-3 gap-6"> {} <div className="bg-slate-50 border border-slate-200 rounded-2xl p-6"> <h4 className="text-xs font-bold text-slate-800 uppercase tracking-widest font-display mb-4 flex items-center"> <Users size={14} className="text-indigo-500 mr-2" /> Collaboration Channels </h4> <div className="space-y-2.5"> {COLLAB_FEATURES.map(feat => <div key={feat.label} className="bg-white p-3 rounded-lg border border-slate-200 flex items-center"> <div className="w-2 h-2 rounded-full bg-indigo-500 mr-3"></div> <span className="text-xs font-bold text-slate-700">{feat.label} Hub</span> </div>)} </div> </div> {} <div className="bg-slate-50 border border-slate-200 rounded-2xl p-6"> <h4 className="text-xs font-bold text-slate-800 uppercase tracking-widest font-display mb-4 flex items-center"> <Layers size={14} className="text-indigo-500 mr-2" /> Data Flow Pipeline </h4> <div className="space-y-2.5"> {DATA_FLOW.map((flow, i) => <div key={flow.label} className="bg-white p-3 rounded-lg border border-slate-200 flex items-center justify-between"> <div className="flex items-center"> <flow.icon size={13} className="text-indigo-500 mr-2.5" /> <span className="text-xs font-bold text-slate-700">{flow.label}</span> </div> <span className="text-[9px] text-slate-400 font-semibold font-display">STAGE {i + 1}</span> </div>)} </div> </div> {} <div className="bg-slate-50 border border-slate-200 rounded-2xl p-6"> <h4 className="text-xs font-bold text-slate-800 uppercase tracking-widest font-display mb-4 flex items-center"> <Layers size={14} className="text-indigo-500 mr-2" /> System Integrations </h4> <div className="space-y-2.5"> {INTEGRATIONS.map(integ => <div key={integ.label} className="bg-white p-3 rounded-lg border border-slate-200 flex items-center"> <div className="p-1.5 bg-indigo-50 rounded mr-3 text-indigo-600"> <integ.icon size={13} /> </div> <span className="text-xs font-bold text-slate-700">{integ.label} Integration</span> </div>)} </div> </div> </div> {} <div className="bg-indigo-50 border border-indigo-100 p-6 rounded-2xl flex flex-col md:flex-row items-center justify-between gap-4"> <div> <h4 className="text-sm font-bold text-indigo-900 font-display">Fully Configured Integrations</h4> <p className="text-xs text-indigo-700 mt-0.5">Bring your existing engineering logs, calendar deadlines, and payment invoices together inside one UI.</p> </div> <button onClick={() => document.getElementById("demo")?.scrollIntoView({
            behavior: "smooth"
          })} className="px-5 py-2 text-xs font-bold text-white bg-indigo-600 hover:bg-indigo-700 rounded-lg shadow-md cursor-pointer transition-colors shrink-0"> Launch Demo Board </button> </div> </div>} </div> </section>;
}
