const PAGE_WIDTH = 595;
const PAGE_HEIGHT = 842;
const MARGIN_X = 54;
const TOP_Y = 790;
const BOTTOM_Y = 56;
const LINE_HEIGHT = 15;
const MAX_TEXT_CHARS = 92;

function cleanText(value) {
  return String(value ?? '')
    .replace(/\u20b9/g, 'INR ')
    .replace(/[^\x20-\x7E]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

function escapePdfText(value) {
  return cleanText(value).replace(/\\/g, '\\\\').replace(/\(/g, '\\(').replace(/\)/g, '\\)');
}

function wrapText(value, maxChars = MAX_TEXT_CHARS) {
  const text = cleanText(value);
  if (!text) return ['-'];

  const words = text.split(' ');
  const lines = [];
  let line = '';

  words.forEach((word) => {
    if (word.length > maxChars) {
      if (line) {
        lines.push(line);
        line = '';
      }
      for (let i = 0; i < word.length; i += maxChars) {
        lines.push(word.slice(i, i + maxChars));
      }
      return;
    }

    const next = line ? `${line} ${word}` : word;
    if (next.length > maxChars) {
      lines.push(line);
      line = word;
    } else {
      line = next;
    }
  });

  if (line) lines.push(line);
  return lines.length ? lines : ['-'];
}

function addText(commands, text, x, y, size = 10) {
  commands.push(`BT /F1 ${size} Tf 1 0 0 1 ${x} ${y} Tm (${escapePdfText(text)}) Tj ET`);
}

function addRule(commands, y) {
  commands.push(`0.78 w ${MARGIN_X} ${y} m ${PAGE_WIDTH - MARGIN_X} ${y} l S`);
}

export function createFormalReportPdf({ title, subtitle, meta = [], sections = [] }) {
  const pages = [];
  let commands = [];
  let y = TOP_Y;

  const startPage = () => {
    commands = [];
    y = TOP_Y;
    commands.push('0.1 0.1 0.1 rg'); // Global default text color: charcoal
    addText(commands, title || 'Report', MARGIN_X, y, 18);
    y -= 20;
    if (subtitle) {
      addText(commands, subtitle, MARGIN_X, y, 10);
      y -= 18;
    }
    addRule(commands, y);
    y -= 18;
  };

  const finishPage = () => {
    addRule(commands, 42);
    addText(commands, `Generated by Syncra SaaS - Page ${pages.length + 1}`, MARGIN_X, 28, 8);
    pages.push(commands.join('\n'));
  };

  const ensureSpace = (needed = LINE_HEIGHT) => {
    if (y - needed >= BOTTOM_Y) return;
    finishPage();
    startPage();
  };

  startPage();

  meta.forEach(([label, value]) => {
    ensureSpace();
    addText(commands, `${label}: ${value || '-'}`, MARGIN_X, y, 10);
    y -= LINE_HEIGHT;
  });

  y -= 6;

  sections.forEach((section) => {
    ensureSpace(34);
    addText(commands, section.heading, MARGIN_X, y, 13);
    y -= 12;
    addRule(commands, y);
    y -= 15;

    if (section.table) {
      const { headers, widths, rows } = section.table;
      
      // Draw Header background
      ensureSpace(22);
      commands.push('0.93 0.94 0.98 rg'); // Light gray-indigo fill
      commands.push(`${MARGIN_X} ${y - 3} ${PAGE_WIDTH - 2 * MARGIN_X} 15 re f`);
      
      // Draw Header text
      commands.push('0.15 0.17 0.22 rg'); // Explicit dark slate fill for header text
      let currX = MARGIN_X + 6;
      headers.forEach((hdr, idx) => {
        addText(commands, hdr, currX, y, 9);
        currX += widths[idx];
      });
      y -= 15;
      
      // Draw Header separator line
      addRule(commands, y);
      y -= 12;
      
      // Draw Rows
      rows.forEach((row) => {
        ensureSpace(16);
        commands.push('0.25 0.28 0.35 rg'); // Explicit charcoal slate fill for row text
        let rowX = MARGIN_X + 6;
        row.forEach((cell, idx) => {
          const cellStr = String(cell || '-');
          addText(commands, cellStr, rowX, y, 8.5);
          rowX += widths[idx];
        });
        
        y -= 4;
        commands.push('0.92 0.93 0.95 RG'); // Subtle light gray border line
        commands.push(`${MARGIN_X} ${y} m ${PAGE_WIDTH - MARGIN_X} ${y} l S`);
        commands.push('0 0 0 RG'); // Reset line color
        y -= 12;
      });
      commands.push('0 0 0 rg'); // Reset fill color to black
      y -= 10;
      return;
    }

    if (!section.rows || section.rows.length === 0) {
      ensureSpace();
      addText(commands, section.emptyText || 'No records available.', MARGIN_X, y, 10);
      y -= LINE_HEIGHT;
      y -= 5;
      return;
    }

    section.rows.forEach((row, index) => {
      ensureSpace(LINE_HEIGHT * 2);
      const prefix = section.numbered === false ? '' : `${index + 1}. `;
      wrapText(`${prefix}${row}`).forEach((line) => {
        ensureSpace();
        addText(commands, line, MARGIN_X, y, 10);
        y -= LINE_HEIGHT;
      });
      y -= 3;
    });

    y -= 6;
  });

  finishPage();

  const objects = [];
  const pageObjects = [];
  const contentObjects = [];

  pages.forEach((content, index) => {
    pageObjects.push(4 + index * 2);
    contentObjects.push(5 + index * 2);
  });

  objects[1] = '<< /Type /Catalog /Pages 2 0 R >>';
  objects[2] = `<< /Type /Pages /Kids [${pageObjects.map((id) => `${id} 0 R`).join(' ')}] /Count ${pages.length} >>`;
  objects[3] = '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>';

  pages.forEach((content, index) => {
    const pageId = pageObjects[index];
    const contentId = contentObjects[index];
    objects[pageId] = `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${PAGE_WIDTH} ${PAGE_HEIGHT}] /Resources << /Font << /F1 3 0 R >> >> /Contents ${contentId} 0 R >>`;
    objects[contentId] = `<< /Length ${content.length} >>\nstream\n${content}\nendstream`;
  });

  let pdf = '%PDF-1.4\n';
  const offsets = [0];

  for (let i = 1; i < objects.length; i += 1) {
    offsets[i] = pdf.length;
    pdf += `${i} 0 obj\n${objects[i]}\nendobj\n`;
  }

  const xrefOffset = pdf.length;
  pdf += `xref\n0 ${objects.length}\n`;
  pdf += '0000000000 65535 f \n';
  for (let i = 1; i < objects.length; i += 1) {
    pdf += `${String(offsets[i]).padStart(10, '0')} 00000 n \n`;
  }
  pdf += `trailer\n<< /Size ${objects.length} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;

  return new Blob([pdf], { type: 'application/pdf' });
}

export function downloadFormalReportPdf(config, filename) {
  const blob = createFormalReportPdf(config);
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename.endsWith('.pdf') ? filename : `${filename}.pdf`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
